#!/bin/csh
#
# Author: Mark Gottscho
# Email: mgottscho@ucla.edu
#
# Last updated 10/4/2015 for EE 201A Fall 2015
#
# Source this script if you are using csh for EE 201A on eeapps.seas.ucla.edu as follows:
# $ source csh_ee201a_setup

# Append OpenAccess binaries to executable path
#setenv PATH ${PATH}:/w/class/ee201a/ee201ata/oa/bin/linux_rhel40_64/opt

# Append OpenAccess libraries to load path
#if ($?LD_LIBRARY_PATH == 0) then
#	setenv LD_LIBRARY_PATH /w/class/ee201a/ee201ata/oa/lib/linux_rhel40_64/opt
#else
#	setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/w/class/ee201a/ee201ata/oa/lib/linux_rhel40_64/opt
#endif

# For OpenAccess Makefiles
#setenv COMPILER_PATH /usr

# For Cadence Encounter Digital Implementation System (EDI aka Encounter)
source /app/apps3/Cadence/EDI110/SETUP

# Append standard library locations
setenv LD_LIBRARY_PATH /usr/lib64:/usr/lib:/lib64:/lib
